name: Check Formatting
on: push
jobs:
  check-formatting:
    name: Check Python and C++ Formatting
    runs-on: ubuntu-latest
    steps:
    - uses: pgrete/cpp-py-formatter/check@v0.4.0
      with:
        clangFormatVersion: 20
        token: ${{ secrets.GITHUB_TOKEN }}
